# Generated by Django 3.0.3 on 2020-02-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField()),
                ('prior', models.SmallIntegerField(blank=True, null=True)),
                ('id_parent', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('name_vi', models.CharField(blank=True, max_length=255, verbose_name='Name_vi')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Name_en')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Unit')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min_value')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max_value')),
                ('string_value', models.CharField(blank=True, max_length=100, verbose_name='String value')),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Sort order')),
                ('type', models.BooleanField(blank=True, default=0, verbose_name='Type')),
                ('status', models.BooleanField(blank=True, default=0, verbose_name='Status')),
                ('is_number', models.BooleanField(blank=True, default=0, verbose_name='Is Number')),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Categories', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order'],
            },
        ),
    ]
